opsnow-tools/valve-ctl

README.md, draft/java-mvn-springboot/charts/acme/templates/deployment.yaml, draft/java-mvn-springboot/charts/acme/templates/hpa.yaml, draft/java-mvn-springboot/charts/acme/values.yaml, draft/java-mvn-tomcat/charts/acme/templates/deployment.yaml, draft/java-mvn-tomcat/charts/acme/templates/hpa.yaml, draft/java-mvn-tomcat/charts/acme/values.yaml, draft/js-npm-nginx/charts/acme/templates/deployment.yaml, draft/js-npm-nginx/charts/acme/templates/hpa.yaml, draft/js-npm-nginx/charts/acme/values.yaml, draft/js-npm-nodejs/charts/acme/templates/deployment.yaml, draft/js-npm-nodejs/charts/acme/templates/hpa.yaml, draft/js-npm-nodejs/charts/acme/values.yaml, draft/web-nginx/charts/acme/templates/deployment.yaml, draft/web-nginx/charts/acme/templates/hpa.yaml, draft/web-nginx/charts/acme/values.yaml, valve.sh
* hpa 를 autoscaling 으로 변경 했습니다.
* hostNetwork, dnsPolicy 를 변수로 받을수 있도록 했습니다.
=> autoscaling, hostNetwork, dnsPolicy

build.sh, draft/java-mvn-springboot/charts/acme/templates/deployment.yaml, draft/java-mvn-springboot/charts/acme/values.yaml, draft/java-mvn-tomcat/charts/acme/templates/deployment.yaml, draft/java-mvn-tomcat/charts/acme/values.yaml, draft/js-npm-nginx/charts/acme/templates/deployment.yaml, draft/js-npm-nginx/charts/acme/values.yaml, draft/js-npm-nodejs/Dockerfile, draft/js-npm-nodejs/charts/acme/templates/deployment.yaml, draft/js-npm-nodejs/charts/acme/values.yaml, draft/web-nginx/charts/acme/templates/deployment.yaml, draft/web-nginx/charts/acme/values.yaml, valve.sh
* pod env 에 NAMESPACE 값을 넘겨 줍니다. app 에서 활용 할수 있도록.
* java 계열 initialDelaySeconds 의 기본값을 30초로 변경 했습니다.
=> add namespace

draft/java-mvn-springboot/charts/acme/values.yaml, draft/java-mvn-tomcat/charts/acme/values.yaml, draft/js-npm-nginx/charts/acme/values.yaml, draft/js-npm-nodejs/charts/acme/values.yaml, draft/web-nginx/charts/acme/values.yaml
base64 인코딩하여 value 에 넣을땐 따옴표로 감싸야 함
=> SECRET: "base64"

valve.sh
fzf option false in window git bash env
=> fzf option false in window git bash env

install.sh, src/valve.sh
Fix install when OS is Windows using git bash
=> Fix error install shell

src/common.sh, src/valve-core/toolbox/install, src/valve-core/toolbox/run.sh, src/valve-plugins/example/run.sh, src/valve.sh
=> Modify comments

src/valve-core/_valve/run.sh, src/valve-core/chart/run.sh, src/valve-core/repo/list, src/valve-core/repo/run.sh
repo object에 대한 list command 구현입니다.
=> Add repo list

src/valve-core/toolbox/install, src/valve-core/toolbox/run.sh
Toolbox install command 추가합니다.
-a/--all
-l/--local
-c/--cluster 
옵션 추가했습니다.
=> Modify toolbox install command / add --all --local --cluster options

src/common.sh, src/valve-core/_template/on, src/valve.sh
valve.sh 
- template object에 대한 command리스트 추가(on / off / ssh / log / top / get)
common.sh
- NAMESPACE 변수 공통 변수로 추가
on
- on 개발
=> Feature dev template on

src/valve-core/_template/off
=> Feature dev template off

src/valve-core/_template/ssh
=> Feature dev template ssh

src/valve-core/_template/log
=> Feature dev template log

src/valve-core/_template/top
=> Feature dev template top

src/valve-core/_template/get
=> Feature dev template get

src/common.sh
- Config 경로를 .valve/valve-ctl 반영
- -vvv옵션에 set -x를 적용
=> Fix reset config common

src/valve-core/repo/remove
=> Feature dev repo remove

src/common.sh, src/valve-core/chart/list, src/valve-core/chart/run.sh
- chart list 개발
- run.sh 에 command 추가
=> Feature dev chart list

src/valve-core/chart/version
=> Feature dev chart version

src/valve-core/_valve/update, src/valve.sh
- _valve object를 사용할 수 있도록 valve.sh 수정
- _valve update 개발
=> Modify valve.sh for using valve object & add update

src/valve-core/_valve/version
=> Add version

src/valve-core/_valve/config
=> Add config

src/valve-core/_template/on
정확한 chart name을 찾아야 했습니다.
이전에는 비슷한 이름을 모두 찾기 때문에 if문이 정확하게 동작하지 않았습니다.
=> Fix exact matching chart name

src/valve-core/_template/log
follow option 시 option을 받도록 되어 있어 오류가 있었습니다.
수정합니다.
=> Fix follow option

src/valve-core/toolbox/install
valve toolbox install --cluster 실행시 _get_yaml 함수가 없어서 에러나는 현상 해결
=> Fix toolbox install cluster option/Add get_yaml private function

src/common.sh, src/valve-core/_template/fetch, src/valve-core/_template/log, src/valve-core/_template/off, src/valve-core/_template/on, src/valve-core/_template/ssh, src/valve-core/chart/tag, src/valve-core/chart/version, src/valve-core/toolbox/install
=> Fix bug with option error

src/valve-core/_template/off
valve off 에서 -v  옵션이 남아있어 이를 수정합니다.
=> Fix valve off error

src/common.sh, src/valve-core/_template/fetch, src/valve-core/_template/search, src/valve-core/toolbox/install, src/valve.sh
- valve-ctl config 외에 config를 만들지 않기 때문에 draft-ls 삭제
- valve search 구현
- valve에서 repo add했을 때 custom template이 ~/.valve/repo/custom 에 저장되는 것에 대한 consensus를 이루었기 때문에 그에 대한 valve fetch 로직의 변경
- 로직 변경으로 인한 불필요한 부분 주석처리(다음 릴리즈에서 삭제할 예정)
=> Feature valve search fetch

src/valve-core/_valve/config
config 를 수정할 수 있도록 제공하는 옵션입니다.
=> Add config edit option

install.sh, src/common.sh, src/valve-core/_template/fetch, src/valve-core/_template/on, src/valve-core/_template/search, src/valve-core/repo/add, src/valve-core/repo/list, src/valve-core/repo/update
repo 관련된 모든 기능들을 전면 수정했습니다.
- install
- Default repository와 Custom repository는 ~/.valve/repo/ 에 위치합니다.
- Default repository 경로는 ~/.valve/repo/valve/templates 입니다.
- install 시 Default repository를 받도록 합니다.
- valve repo add
- valve repo add시 Custom repository를 받도록 합니다.
- valve repo list
- valve repo list를 간단하게 수정했습니다.
- valve repo list시 Default repo와 Custom repo를 모두 보여줍니다.
- valve search
- valve search 또한 간단하게 수정했습니다.
- valve fetch
- valve fetch 시 values.yaml 에 image repository URL을 치환하는 것을 삭제했습니다.
- valve on
- valve on 시 values.yaml에 image repository URL을 치환하도록 했습니다.
=> Modify install.sh, common.sh, fetch, on, search, repo

src/common.sh, src/valve-core/chart/version
- valve chart version 은 -n 을 입력받도록 해야 동작하는데 valve chart version 만 했을 때 동작하여 수정
- chartmuseum 변수값을 받지 못해와서 common.sh 을 수정
=> Fix error valve chart version

install.sh
USERNAME 이라는 변수가 되지 않는 이슈.
USERNAME -> GROUPNAME으로 변경
=> Fix error when install valve-ctl -> username variable error

src/valve-core/toolbox/install
=> Update toolbox list

src/valve-core/_template/log, src/valve-core/_template/ssh, src/valve-core/_template/top
=> Fix error valve top if -v option to -z option

src/valve-core/chart/tag, src/valve-core/toolbox/install
- `valve chart tag` command 실행 시 tag untag 시 로직이 문제가 있어 수정
- helm push를 위해 plugin 설치를 toolbox install 시 설치하도록 수정
=> Feature toolbox install addhelmpush

.github/CODEOWNERS
=> Add contributor

README.md, src/valve.sh
=> Feature main help

src/valve-core/_template/on, src/valve-core/toolbox/install
- valve on시 external chart 의 tag가 stable인 것만 땡겨오는 것을 삭제했습니다.
- toolbox install 시 이상하게 설치되는 것 수정했습니다.(helm / tfenv)
- toolbox install시 config를 aws-cli / aws-iam-authenticator 추가했습니다.
- toolbox install시 OS TYPE이 windows 일 때를 추가했습니다.
- toolbox install 시 config를 추가/수정하는 부분을 수정했습니다.
=> Fix toolbox install on update

src/valve-core/_template/get
사용자에게 app을 배포하고 나서 배포한 URL을 보여주는 command option이 없어 
개발합니다.
=> Feature add valve get -i|--ing

src/valve.sh
valve command를 잘못 적었을 때 valve help를 사용하도록 하는 error문을 추가합니다.
=> Modify valve help

src/valve-core/_template/get, src/valve.sh
- valve get 했을 때 여러 옵션이 동작하도록 변경
- 안됐던 이유는 _success 함수가 각 함수마다 설정이 되어있었다.
- 현재 정의된 valve command 가 아닌 command 실행시 오류가 나도록 다시 수정
- *(스타) 로 case를 정의해서 모든 command 실행 시 계속 에러메시지가 뜸
=> Hot fix error -- valve get & valve error command

src/valve-core/_template/fetch, src/valve-core/_template/search, src/valve-core/repo/remove
- valve repo remove 시 success 로그 문구가 이상한 것 수정
- valve search시 template git의 구조가 templates라는 폴더를 만들고 그 안에 template들이 위치하는 구조인 것을 고려하여 logic을 변경함
=> Modify valve repo remove / Modify valve search logic

src/valve-core/_template/get
valve get --ing | valve get -i 실행 시 kubectl 나오는 그대로 나오도록 변경
=> Modify valve get ingress

src/valve-plugins/example/example, src/valve-plugins/example/run.sh
valve plugin 으로 개발시 help에 command가 뜨도록 변경
=> Modify valve-plugin help

src/valve-plugins/example/run.sh, src/valve.sh
- valve help 시 무의미한 command 나열을 삭제
- valve help 시 plugin 에 대한 command와 description을 보여주도록 수정
- description은 각 plugin object의 help를 가져오도록 함.
=> Modify valve help - add plugin help

src/valve-core/_template/fetch, src/valve-core/_template/log, src/valve-core/_template/ssh
help 의 순서를 변경하고 미진한 부분들을 수정합니다.
=> Modify help options order

install.sh, src/valve-core/_template/on, src/valve-core/toolbox/install
1. getopt 방어 코드 구현
2. docker 명령어시 sudo 앞에 추가
3. helm 3.0 설치 되지 않도록 방어 코드 구현
=> Hot fix#2 1. Defense getopt install 2. sudo docker 3. helm 3.0

install.sh
- 기존 path에 공백이 있을 경우 처리못하는 오류 수정
=> bug fix - path cant include space

src/common.sh, src/valve.sh
=> Feature sentry

src/common.sh, src/valve-core/toolbox/install
sentry log level 표시하는 변수 누락 부분 보강
toolbox install  할 때 os_type 체크하는 부분 변경
=> add log level

src/valve-core/toolbox/install
=> typing error fix

src/valve.sh
help 호출할 때 exit 1로 호출되는 부분을 exit 0로 호출되도록 수정
=> remove error when calling help

src/common.sh, src/valve.sh
- valve를 수행한 뒤 마지막 결과 수집 log
- 유저가 입력한 파라메터 수집
=> add logfile & get user parameters

src/common.sh, src/valve.sh
- 센트리 관련 화면 출력 부분삭제
- exit 0이외 센트리로 이중 전송 부분 수정
- valve 이후 입력 값이 없을 경우 오동작 방지
help 이후 exit0를 하지 않을 경우 198~199라인에서 CMD값이 null인 상태로 수행되면서 오동작함.
이에 help이 후 exit 0를 넣어 정상 종료로 처리함
=> output modified about sentry

src/common.sh, src/valve-core/_template/fetch, src/valve-core/_template/get, src/valve-core/_template/log, src/valve-core/_template/off, src/valve-core/_template/on, src/valve-core/_template/search, src/valve-core/_template/ssh, src/valve-core/_template/top, src/valve-core/_valve/config, src/valve-core/_valve/run.sh, src/valve-core/_valve/update, src/valve-core/_valve/version, src/valve-core/chart/list, src/valve-core/chart/run.sh, src/valve-core/chart/tag, src/valve-core/chart/version, src/valve-core/repo/add, src/valve-core/repo/remove, src/valve-core/repo/run.sh, src/valve-core/repo/update, src/valve-core/toolbox/install, src/valve-core/toolbox/run.sh, src/valve.sh
bash command을 수행 후 exit code를 검사하는 루틴 삽입
script에서 호출하는 외부 command의 수행 결과를 검사하여 프로그램에서 대응할 수 있도록 함
예제로 toolbox install 부분을 수정함
깨끗한 우분투를 대상을 실행하면 tfenv를 설치하면서 장애가 발생했다고 경고를 출력하면서 종료되는 모습을 볼 수 있음
=> command 호출 후 exit 확인하는 코드 삽입

src/valve-core/_template/get, src/valve-core/_template/on, src/valve-core/_template/top, src/valve-core/_valve/update, src/valve-core/chart/list, src/valve-core/chart/tag, src/valve-core/repo/add, src/valve-core/repo/list, src/valve-core/repo/remove, src/valve-core/repo/update, src/valve-plugins/example/example, src/valve-plugins/example/run.sh
valve ctl에서 호출하는 모든 명령어들의 exit code를 검사하는 루틴 삽입.
=> command exit code 검사 루틴 삽입
